name: QuickShop-Era
version: ${project.version}
main: com.github.bukkitcommmons.QuickShop
authors:
  - portlek
api-version: '1.13'
description: ${project.description}
depend:
  - Vault
commands:
  quickshop:
